"""add score to resume analysis

Revision ID: ad5d7738cc45
Revises: aad9fe7c4f11
Create Date: 2026-06-01 15:18:08.985232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5d7738cc45'
down_revision = 'aad9fe7c4f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_analysis', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###
